export const branches = [
    { label: 'SPO', value: '1' },
    { label: 'REC', value: '2' },
    { label: 'SSA', value: '3' },
    { label: 'FOR', value: '4' },
    { label: 'MCZ', value: '5' },
    { label: 'NAT', value: '6' },
    { label: 'JPA', value: '7' },
    { label: 'AJU', value: '8' },
    { label: 'VDC', value: '9' },
    { label: 'CTG', value: '10' },
    { label: 'GVR', value: '11' },
    { label: 'VIX', value: '12' },
    { label: 'TCO', value: '13' },
    { label: 'UDI', value: '14' },
    { label: 'BMA', value: '15' },
    { label: 'BPE', value: '16' },
    { label: 'BEL', value: '17' },
    { label: 'BPB', value: '18' },
    { label: 'SLZ', value: '19' },
    { label: 'BAL', value: '20' },
    { label: 'THE', value: '21' },
    { label: 'BMG', value: '22' },
    { label: 'FMA', value: '23' },
    { label: 'JSR', value: '24' },
    { label: 'JC', value: '25' },
].map(item => ({ label: item.label, value: item.value }));